import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const directory = 'src/assets/law-firm';
const output = `${directory}/responsive`;
await fs.mkdir(output, { recursive: true });
const imports = [];
const entries = [];
const mobileEntries = [];
let index = 0;
for (const file of (await fs.readdir(directory)).sort()) {
  if (!/\.(jpg|avif|webp)$/.test(file)) continue;
  const source = `${directory}/${file}`;
  const metadata = await sharp(source).metadata();
  const name = path.parse(file).name;
  const original = `image${index++}`;
  imports.push(`import ${original} from '@/assets/law-firm/${file}';`);
  const variants = [];
  for (const width of [96, 480, 960, 1440]) {
    if (width >= metadata.width) continue;
    const variant = `${name}-${width}.webp`;
    await sharp(source).rotate().resize({ width, withoutEnlargement: true }).webp({ quality: 80, effort: 6 }).toFile(`${output}/${variant}`);
    const id = `image${index++}`;
    imports.push(`import ${id} from '@/assets/law-firm/responsive/${variant}';`);
    variants.push(`\`${'${'}${id}} ${width}w\``);
  }
  variants.push(`\`${'${'}${original}} ${metadata.width}w\``);
  entries.push(`  [${original}]: { srcSet: [${variants.join(', ')}].join(', '), width: ${metadata.width}, height: ${metadata.height} },`);
  if (name.startsWith('hero-')) {
    const mobile = [];
    for (const width of [540, 810]) {
      const variant = `${name}-mobile-${width}.webp`;
      // Keep the scene's subject on the right, removing empty desktop text space.
      await sharp(source).rotate().resize(width, Math.round(width * 16 / 9), { fit: 'cover', position: 'right' }).webp({ quality: 80, effort: 6 }).toFile(`${output}/${variant}`);
      const id = `image${index++}`;
      imports.push(`import ${id} from '@/assets/law-firm/responsive/${variant}';`);
      mobile.push(`\`${'${'}${id}} ${width}w\``);
    }
    mobileEntries.push(`  [${original}]: [${mobile.join(', ')}].join(', '),`);
  }
}
await fs.writeFile('src/lib/responsive-image-data.ts', '// Generated by npm run images:generate.\n' + imports.join('\n') + '\nexport const imageVariants: Record<string, { srcSet: string; width: number; height: number }> = {\n' + entries.join('\n') + '\n};\nexport const mobileHeroVariants: Record<string, string> = {\n' + mobileEntries.join('\n') + '\n};\n');
