/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AttorneyRouteImport } from './routes/attorney'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as CaseValueCalculatorRouteImport } from './routes/case-value-calculator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as KoRouteImport } from './routes/ko'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as PracticeAreasRouteImport } from './routes/practice-areas'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as BlogsSlugRouteImport } from './routes/blogs_.$slug'
import { Route as KoAboutRouteImport } from './routes/ko_.about'
import { Route as KoAccessibilityRouteImport } from './routes/ko_.accessibility'
import { Route as KoAttorneyRouteImport } from './routes/ko_.attorney'
import { Route as KoBlogsRouteImport } from './routes/ko_.blogs'
import { Route as KoCaseValueCalculatorRouteImport } from './routes/ko_.case-value-calculator'
import { Route as KoContactRouteImport } from './routes/ko_.contact'
import { Route as KoDisclaimerRouteImport } from './routes/ko_.disclaimer'
import { Route as KoLocationsRouteImport } from './routes/ko_.locations'
import { Route as KoPracticeAreasRouteImport } from './routes/ko_.practice-areas'
import { Route as KoPrivacyPolicyRouteImport } from './routes/ko_.privacy-policy'
import { Route as KoResultsRouteImport } from './routes/ko_.results'
import { Route as KoTermsRouteImport } from './routes/ko_.terms'
import { Route as KoThankYouRouteImport } from './routes/ko_.thank-you'
import { Route as LocationsSlugRouteImport } from './routes/locations_.$slug'
import { Route as PracticeAreasSlugRouteImport } from './routes/practice-areas_.$slug'
import { Route as KoBlogsSlugRouteImport } from './routes/ko_.blogs_.$slug'
import { Route as KoLocationsSlugRouteImport } from './routes/ko_.locations_.$slug'
import { Route as KoPracticeAreasSlugRouteImport } from './routes/ko_.practice-areas_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AttorneyRoute = AttorneyRouteImport.update({
  id: '/attorney',
  path: '/attorney',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseValueCalculatorRoute = CaseValueCalculatorRouteImport.update({
  id: '/case-value-calculator',
  path: '/case-value-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const KoRoute = KoRouteImport.update({
  id: '/ko',
  path: '/ko',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAreasRoute = PracticeAreasRouteImport.update({
  id: '/practice-areas',
  path: '/practice-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs_/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KoAboutRoute = KoAboutRouteImport.update({
  id: '/ko_/about',
  path: '/ko/about',
  getParentRoute: () => rootRouteImport,
} as any)
const KoAccessibilityRoute = KoAccessibilityRouteImport.update({
  id: '/ko_/accessibility',
  path: '/ko/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const KoAttorneyRoute = KoAttorneyRouteImport.update({
  id: '/ko_/attorney',
  path: '/ko/attorney',
  getParentRoute: () => rootRouteImport,
} as any)
const KoBlogsRoute = KoBlogsRouteImport.update({
  id: '/ko_/blogs',
  path: '/ko/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const KoCaseValueCalculatorRoute = KoCaseValueCalculatorRouteImport.update({
  id: '/ko_/case-value-calculator',
  path: '/ko/case-value-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const KoContactRoute = KoContactRouteImport.update({
  id: '/ko_/contact',
  path: '/ko/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const KoDisclaimerRoute = KoDisclaimerRouteImport.update({
  id: '/ko_/disclaimer',
  path: '/ko/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const KoLocationsRoute = KoLocationsRouteImport.update({
  id: '/ko_/locations',
  path: '/ko/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const KoPracticeAreasRoute = KoPracticeAreasRouteImport.update({
  id: '/ko_/practice-areas',
  path: '/ko/practice-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const KoPrivacyPolicyRoute = KoPrivacyPolicyRouteImport.update({
  id: '/ko_/privacy-policy',
  path: '/ko/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const KoResultsRoute = KoResultsRouteImport.update({
  id: '/ko_/results',
  path: '/ko/results',
  getParentRoute: () => rootRouteImport,
} as any)
const KoTermsRoute = KoTermsRouteImport.update({
  id: '/ko_/terms',
  path: '/ko/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const KoThankYouRoute = KoThankYouRouteImport.update({
  id: '/ko_/thank-you',
  path: '/ko/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations_/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAreasSlugRoute = PracticeAreasSlugRouteImport.update({
  id: '/practice-areas_/$slug',
  path: '/practice-areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KoBlogsSlugRoute = KoBlogsSlugRouteImport.update({
  id: '/ko_/blogs_/$slug',
  path: '/ko/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KoLocationsSlugRoute = KoLocationsSlugRouteImport.update({
  id: '/ko_/locations_/$slug',
  path: '/ko/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KoPracticeAreasSlugRoute = KoPracticeAreasSlugRouteImport.update({
  id: '/ko_/practice-areas_/$slug',
  path: '/ko/practice-areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/attorney': typeof AttorneyRoute
  '/blogs': typeof BlogsRoute
  '/case-value-calculator': typeof CaseValueCalculatorRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/ko': typeof KoRoute
  '/locations': typeof LocationsRoute
  '/practice-areas': typeof PracticeAreasRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/results': typeof ResultsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/ko/about': typeof KoAboutRoute
  '/ko/accessibility': typeof KoAccessibilityRoute
  '/ko/attorney': typeof KoAttorneyRoute
  '/ko/blogs': typeof KoBlogsRoute
  '/ko/case-value-calculator': typeof KoCaseValueCalculatorRoute
  '/ko/contact': typeof KoContactRoute
  '/ko/disclaimer': typeof KoDisclaimerRoute
  '/ko/locations': typeof KoLocationsRoute
  '/ko/practice-areas': typeof KoPracticeAreasRoute
  '/ko/privacy-policy': typeof KoPrivacyPolicyRoute
  '/ko/results': typeof KoResultsRoute
  '/ko/terms': typeof KoTermsRoute
  '/ko/thank-you': typeof KoThankYouRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/practice-areas/$slug': typeof PracticeAreasSlugRoute
  '/ko/blogs/$slug': typeof KoBlogsSlugRoute
  '/ko/locations/$slug': typeof KoLocationsSlugRoute
  '/ko/practice-areas/$slug': typeof KoPracticeAreasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/attorney': typeof AttorneyRoute
  '/blogs': typeof BlogsRoute
  '/case-value-calculator': typeof CaseValueCalculatorRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/ko': typeof KoRoute
  '/locations': typeof LocationsRoute
  '/practice-areas': typeof PracticeAreasRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/results': typeof ResultsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/ko/about': typeof KoAboutRoute
  '/ko/accessibility': typeof KoAccessibilityRoute
  '/ko/attorney': typeof KoAttorneyRoute
  '/ko/blogs': typeof KoBlogsRoute
  '/ko/case-value-calculator': typeof KoCaseValueCalculatorRoute
  '/ko/contact': typeof KoContactRoute
  '/ko/disclaimer': typeof KoDisclaimerRoute
  '/ko/locations': typeof KoLocationsRoute
  '/ko/practice-areas': typeof KoPracticeAreasRoute
  '/ko/privacy-policy': typeof KoPrivacyPolicyRoute
  '/ko/results': typeof KoResultsRoute
  '/ko/terms': typeof KoTermsRoute
  '/ko/thank-you': typeof KoThankYouRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/practice-areas/$slug': typeof PracticeAreasSlugRoute
  '/ko/blogs/$slug': typeof KoBlogsSlugRoute
  '/ko/locations/$slug': typeof KoLocationsSlugRoute
  '/ko/practice-areas/$slug': typeof KoPracticeAreasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/attorney': typeof AttorneyRoute
  '/blogs': typeof BlogsRoute
  '/case-value-calculator': typeof CaseValueCalculatorRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/ko': typeof KoRoute
  '/locations': typeof LocationsRoute
  '/practice-areas': typeof PracticeAreasRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/results': typeof ResultsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/blogs_/$slug': typeof BlogsSlugRoute
  '/ko_/about': typeof KoAboutRoute
  '/ko_/accessibility': typeof KoAccessibilityRoute
  '/ko_/attorney': typeof KoAttorneyRoute
  '/ko_/blogs': typeof KoBlogsRoute
  '/ko_/case-value-calculator': typeof KoCaseValueCalculatorRoute
  '/ko_/contact': typeof KoContactRoute
  '/ko_/disclaimer': typeof KoDisclaimerRoute
  '/ko_/locations': typeof KoLocationsRoute
  '/ko_/practice-areas': typeof KoPracticeAreasRoute
  '/ko_/privacy-policy': typeof KoPrivacyPolicyRoute
  '/ko_/results': typeof KoResultsRoute
  '/ko_/terms': typeof KoTermsRoute
  '/ko_/thank-you': typeof KoThankYouRoute
  '/locations_/$slug': typeof LocationsSlugRoute
  '/practice-areas_/$slug': typeof PracticeAreasSlugRoute
  '/ko_/blogs_/$slug': typeof KoBlogsSlugRoute
  '/ko_/locations_/$slug': typeof KoLocationsSlugRoute
  '/ko_/practice-areas_/$slug': typeof KoPracticeAreasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/attorney'
    | '/blogs'
    | '/case-value-calculator'
    | '/contact'
    | '/disclaimer'
    | '/ko'
    | '/locations'
    | '/practice-areas'
    | '/privacy-policy'
    | '/results'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/blogs/$slug'
    | '/ko/about'
    | '/ko/accessibility'
    | '/ko/attorney'
    | '/ko/blogs'
    | '/ko/case-value-calculator'
    | '/ko/contact'
    | '/ko/disclaimer'
    | '/ko/locations'
    | '/ko/practice-areas'
    | '/ko/privacy-policy'
    | '/ko/results'
    | '/ko/terms'
    | '/ko/thank-you'
    | '/locations/$slug'
    | '/practice-areas/$slug'
    | '/ko/blogs/$slug'
    | '/ko/locations/$slug'
    | '/ko/practice-areas/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/attorney'
    | '/blogs'
    | '/case-value-calculator'
    | '/contact'
    | '/disclaimer'
    | '/ko'
    | '/locations'
    | '/practice-areas'
    | '/privacy-policy'
    | '/results'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/blogs/$slug'
    | '/ko/about'
    | '/ko/accessibility'
    | '/ko/attorney'
    | '/ko/blogs'
    | '/ko/case-value-calculator'
    | '/ko/contact'
    | '/ko/disclaimer'
    | '/ko/locations'
    | '/ko/practice-areas'
    | '/ko/privacy-policy'
    | '/ko/results'
    | '/ko/terms'
    | '/ko/thank-you'
    | '/locations/$slug'
    | '/practice-areas/$slug'
    | '/ko/blogs/$slug'
    | '/ko/locations/$slug'
    | '/ko/practice-areas/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/attorney'
    | '/blogs'
    | '/case-value-calculator'
    | '/contact'
    | '/disclaimer'
    | '/ko'
    | '/locations'
    | '/practice-areas'
    | '/privacy-policy'
    | '/results'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/blogs_/$slug'
    | '/ko_/about'
    | '/ko_/accessibility'
    | '/ko_/attorney'
    | '/ko_/blogs'
    | '/ko_/case-value-calculator'
    | '/ko_/contact'
    | '/ko_/disclaimer'
    | '/ko_/locations'
    | '/ko_/practice-areas'
    | '/ko_/privacy-policy'
    | '/ko_/results'
    | '/ko_/terms'
    | '/ko_/thank-you'
    | '/locations_/$slug'
    | '/practice-areas_/$slug'
    | '/ko_/blogs_/$slug'
    | '/ko_/locations_/$slug'
    | '/ko_/practice-areas_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AttorneyRoute: typeof AttorneyRoute
  BlogsRoute: typeof BlogsRoute
  CaseValueCalculatorRoute: typeof CaseValueCalculatorRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  KoRoute: typeof KoRoute
  LocationsRoute: typeof LocationsRoute
  PracticeAreasRoute: typeof PracticeAreasRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResultsRoute: typeof ResultsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  KoAboutRoute: typeof KoAboutRoute
  KoAccessibilityRoute: typeof KoAccessibilityRoute
  KoAttorneyRoute: typeof KoAttorneyRoute
  KoBlogsRoute: typeof KoBlogsRoute
  KoCaseValueCalculatorRoute: typeof KoCaseValueCalculatorRoute
  KoContactRoute: typeof KoContactRoute
  KoDisclaimerRoute: typeof KoDisclaimerRoute
  KoLocationsRoute: typeof KoLocationsRoute
  KoPracticeAreasRoute: typeof KoPracticeAreasRoute
  KoPrivacyPolicyRoute: typeof KoPrivacyPolicyRoute
  KoResultsRoute: typeof KoResultsRoute
  KoTermsRoute: typeof KoTermsRoute
  KoThankYouRoute: typeof KoThankYouRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  PracticeAreasSlugRoute: typeof PracticeAreasSlugRoute
  KoBlogsSlugRoute: typeof KoBlogsSlugRoute
  KoLocationsSlugRoute: typeof KoLocationsSlugRoute
  KoPracticeAreasSlugRoute: typeof KoPracticeAreasSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attorney': {
      id: '/attorney'
      path: '/attorney'
      fullPath: '/attorney'
      preLoaderRoute: typeof AttorneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-value-calculator': {
      id: '/case-value-calculator'
      path: '/case-value-calculator'
      fullPath: '/case-value-calculator'
      preLoaderRoute: typeof CaseValueCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko': {
      id: '/ko'
      path: '/ko'
      fullPath: '/ko'
      preLoaderRoute: typeof KoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-areas': {
      id: '/practice-areas'
      path: '/practice-areas'
      fullPath: '/practice-areas'
      preLoaderRoute: typeof PracticeAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs_/$slug': {
      id: '/blogs_/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko_/about': {
      id: '/ko_/about'
      path: '/ko/about'
      fullPath: '/ko/about'
      preLoaderRoute: typeof KoAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko_/accessibility': {
      id: '/ko_/accessibility'
      path: '/ko/accessibility'
      fullPath: '/ko/accessibility'
      preLoaderRoute: typeof KoAccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko_/attorney': {
      id: '/ko_/attorney'
      path: '/ko/attorney'
      fullPath: '/ko/attorney'
      preLoaderRoute: typeof KoAttorneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko_/blogs': {
      id: '/ko_/blogs'
      path: '/ko/blogs'
      fullPath: '/ko/blogs'
      preLoaderRoute: typeof KoBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko_/case-value-calculator': {
      id: '/ko_/case-value-calculator'
      path: '/ko/case-value-calculator'
      fullPath: '/ko/case-value-calculator'
      preLoaderRoute: typeof KoCaseValueCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko_/contact': {
      id: '/ko_/contact'
      path: '/ko/contact'
      fullPath: '/ko/contact'
      preLoaderRoute: typeof KoContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko_/disclaimer': {
      id: '/ko_/disclaimer'
      path: '/ko/disclaimer'
      fullPath: '/ko/disclaimer'
      preLoaderRoute: typeof KoDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko_/locations': {
      id: '/ko_/locations'
      path: '/ko/locations'
      fullPath: '/ko/locations'
      preLoaderRoute: typeof KoLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko_/practice-areas': {
      id: '/ko_/practice-areas'
      path: '/ko/practice-areas'
      fullPath: '/ko/practice-areas'
      preLoaderRoute: typeof KoPracticeAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko_/privacy-policy': {
      id: '/ko_/privacy-policy'
      path: '/ko/privacy-policy'
      fullPath: '/ko/privacy-policy'
      preLoaderRoute: typeof KoPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko_/results': {
      id: '/ko_/results'
      path: '/ko/results'
      fullPath: '/ko/results'
      preLoaderRoute: typeof KoResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko_/terms': {
      id: '/ko_/terms'
      path: '/ko/terms'
      fullPath: '/ko/terms'
      preLoaderRoute: typeof KoTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko_/thank-you': {
      id: '/ko_/thank-you'
      path: '/ko/thank-you'
      fullPath: '/ko/thank-you'
      preLoaderRoute: typeof KoThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations_/$slug': {
      id: '/locations_/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-areas_/$slug': {
      id: '/practice-areas_/$slug'
      path: '/practice-areas/$slug'
      fullPath: '/practice-areas/$slug'
      preLoaderRoute: typeof PracticeAreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko_/blogs_/$slug': {
      id: '/ko_/blogs_/$slug'
      path: '/ko/blogs/$slug'
      fullPath: '/ko/blogs/$slug'
      preLoaderRoute: typeof KoBlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko_/locations_/$slug': {
      id: '/ko_/locations_/$slug'
      path: '/ko/locations/$slug'
      fullPath: '/ko/locations/$slug'
      preLoaderRoute: typeof KoLocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko_/practice-areas_/$slug': {
      id: '/ko_/practice-areas_/$slug'
      path: '/ko/practice-areas/$slug'
      fullPath: '/ko/practice-areas/$slug'
      preLoaderRoute: typeof KoPracticeAreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AttorneyRoute: AttorneyRoute,
  BlogsRoute: BlogsRoute,
  CaseValueCalculatorRoute: CaseValueCalculatorRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  KoRoute: KoRoute,
  LocationsRoute: LocationsRoute,
  PracticeAreasRoute: PracticeAreasRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResultsRoute: ResultsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  KoAboutRoute: KoAboutRoute,
  KoAccessibilityRoute: KoAccessibilityRoute,
  KoAttorneyRoute: KoAttorneyRoute,
  KoBlogsRoute: KoBlogsRoute,
  KoCaseValueCalculatorRoute: KoCaseValueCalculatorRoute,
  KoContactRoute: KoContactRoute,
  KoDisclaimerRoute: KoDisclaimerRoute,
  KoLocationsRoute: KoLocationsRoute,
  KoPracticeAreasRoute: KoPracticeAreasRoute,
  KoPrivacyPolicyRoute: KoPrivacyPolicyRoute,
  KoResultsRoute: KoResultsRoute,
  KoTermsRoute: KoTermsRoute,
  KoThankYouRoute: KoThankYouRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  PracticeAreasSlugRoute: PracticeAreasSlugRoute,
  KoBlogsSlugRoute: KoBlogsSlugRoute,
  KoLocationsSlugRoute: KoLocationsSlugRoute,
  KoPracticeAreasSlugRoute: KoPracticeAreasSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
